### ISSUE TITLE
Sync Not Working Since Mid-Nov

### ISSUE THREAD

**Issue by Ballou** [cpfair/tapiriik#193]
Myself and others reporting on Twitter that sync is not working for a while now. I sync only GC to a subfolder in DB. Temporary fix is to disable accounts in Tapiriik and enable them again. Results in a single activity sync, or an attempt to sync all old activities (if you don't adjust the preference date). After that initial sync, future syncs continue an endless queue cycle with no actual sync.

**Comment by bobharner** [comment]
Me too, with Endomondo/Strava manual sync, nothing syncs since Nov 25, and no error.

**Comment by Ballou** [comment]
Know this issue started for folks right as the holidays came on, and I suspect why it has not been addressed. The developer is otherwise communicative via email & Twitter. Hope to see this addressed soon.

**Comment by runningsocks** [comment]
me too. since 20.11.2015 there is nothing syncing from my endomondo to strava. i wrote twice to collin fair, but get no answer. i deleted all activities from endo on 20.11., but nothing is syncing. i don't know what to do. i disconnected and connected again all services, nothing was syncing. and it seems, since last update on tapiriik there is no list of synced activities visible ....

**Comment by cpfair** [comment]
Here's the story, and I'll say up-front that I am sorry for not looking into this sooner. https://github.com/cpfair/tapiriik/commit/fbbbc9cdd0d01ea05a769c5d204f09ea553dab9b (Nov 7) introduced this issue, fixed in https://github.com/cpfair/tapiriik/commit/b958e7fd73f448ffb80873b90f191d8d25839075e.

It caused all incoming notifications from Endomondo about new activities to disappear into a black hole, as the workers processing those tasks were failing as soon as the data arrived (due to a silly issue with how logging was being handled - see above commits). Reconnecting your account would indeed make it work temporarily, as the system would perform a full re-index of the account before going back to the  notification system. This also affected Garmin Connect users, though to a lesser degree due to how GC's activity polling works.

Anyways, the fix has been deployed and things appear to be working. All GC & Endomondo users will having their accounts fully reindexed at next synchronization, at which point missing activities will by synchronized.

I'm now looking into ways to automatically monitor these background processes. The failures weren't immediately flagged because they were being trapped by celery's task runner and never precipitated in actual process crashes or unusual MQ traffic. The Endomondo integration has never been rock solid, so I assumed this report (and others for the same issue) were just transient rate-limiting issues/remote failures.

**Comment by kanokc** [comment]
Same here.  Strava-Endomondo-Runkeeper sync was freeze.

**Comment by wwcsig** [comment]
Are you sure that all Endomondo trouble is taken care off?  50% of my 2013 and 2014 workouts in Endomondo are not being transferred. 
For about a week their status is:  Dropbox: Some services limit how many actions tapiriik can perform on your behalf per hour - more activities will transfer soon. 
And my tapiriik setup is just two accounts: Endomondo: sync to Dropbox, Dropbox: sync to none.

**Comment by hoedinie** [comment]
Since last week my synchronization keeps telling "Checking Endomondo". Nothing has been synced since that time

**Comment by runningsocks** [comment]
Hi guy's. Same is with Strava. Since 08.01.2016 i only see "Checking
Strava", but nothing happens. No sync. 

btw: from 20.11.2015 to 20.12.2015 there are also no syncs between
strava and/or endomondo. 

Am 14.01.2016 14:24, schrieb hoedinie: 

> Since last week my synchronization keeps telling "Checking Endomondo". Nothing has been synced since that time 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/cpfair/tapiriik/issues/193#issuecomment-171643349

**Comment by vhpietil** [comment]
Hi, I also have several activites in Endomondo that have not been synced. UI says that "This activity was not synchronized to the following services:
Strava: You've excluded this activity from synchronizing to Strava."

I don't know that I have done something to exlude these activities. Is there something I could do to enable include them?

**Comment by mcerincorporated** [comment]
Hi, for me it is continually saying 'checking garmin connect',  I can't get rid of it and nothing is syncing since 23 Dec. Is there any fix?

**Comment by Ballou** [comment]
Been resolved for me & working reliably since the developer replied to this thread about a month ago. Sorry I didn't close the ticket. Others may want to start a new issue report.
