### ISSUE TITLE
Garmin Connect workout name is Untitled

### ISSUE THREAD

**Issue by cuh7b5** [cpfair/tapiriik#197]
Hello,
I am syncing my tcx files from Dropbox to GC, Runkeeper and Endomondo. For a while the title of the workouts are not synced to Garmin Connect. The workout with all its data appears fine under GC but its title is always "Untitled". The names are correctly synced to Runkeeper and Endomondo. 

Anyone experiencig the same? Is there a way to fix this? Thx

**Comment by MattB111** [comment]
Yes i have exactly the same. All my runs/rides are uploaded to Strava and I use tapiriik to sync to Garmin Connect.

The last activity in Garmin Connect was from 13th December. All other activities since then are just named "Untitled".

I've checked my wife's account and that is exactly the same. The last activity with the correct name synced on 13th December, but everything after is titled "Untitled".

**Comment by MattB111** [comment]
I assume you made a change, as for the first time since 13th December a run has transferred from Strava to Garmin Connect and it has the correct name.

Thanks for the great work.

**Comment by cuh7b5** [comment]
I can confirm, it works again! I believe that they corrected the API at Garmin Connect. Anyway, problem solved.
