### ISSUE TITLE
Duplicates since I turned on Strava and BeginnerTriathlete.com

### ISSUE THREAD

**Issue by richarddavenport** [cpfair/tapiriik#241]
I have had Runkeeper, Endomondo, Dropbox and Garmin syncing for a while now without any issues. A month or so ago I turned on Strava and BeginnerTriathlete.com. I'm not sure when it happened, but now all of my workouts have been duplicated, even the ones all the way back to 2014. What's strange is that it will say the same activity and day and it looks like even the start times are the same. The thing that's different is the activity duration and the duplicate has zero GPS data. Did I stumble upon a bug? Is there a way to batch fix this? Thanks!

**Comment by richarddavenport** [comment]
Well that didn't help... I remove BeginnerTriathlete.com and now there are three of every activity!
@cpfair any reason for this you can think of?
Strava screenshot:
<img width="1158" alt="rad 2016-07-11 at 8 35 54 am" src="https://cloud.githubusercontent.com/assets/3596012/16732421/b648765a-4742-11e6-935e-154663b37cb2.png">
Tapiriik screenshot:
<img width="912" alt="rad 2016-07-11 at 8 37 07 am" src="https://cloud.githubusercontent.com/assets/3596012/16732443/d319402a-4742-11e6-97fe-b344be892100.png">

**Comment by cpfair** [comment]
There appears to be a bug in the BeginnerTriathlete module ( @mattsummers ) that handles user timezones backwards, e.g. GMT+6 instead of GMT-6. This, combined with certain service's rounding of the timestamps to the nearest minute caused them to be treated as different activities. I just made a change to address the latter issue in 5a84c94.

You can use this tool https://tapiriik.com/rollback to automatically delete *all* activities tapiriik has ever uploaded to your Strava, GC, and BT accounts. Unfortunately the same does not exist for RunKeeper at the moment as the API access I have does not include the ability to delete activities.

**Comment by mattsummers** [comment]
Thanks, Colin. I will submit a change shortly. Sorry for the trouble.

**Comment by richarddavenport** [comment]
Thanks @cpfair I've been trying to fetch the activities, but its just saying "Fetching list (it'll take a bit)". I've let it sit for a few hours, but I haven't been able to get the list of activities. Anything else I need to do?

**Comment by richarddavenport** [comment]
Kept trying, eventually got it. Thanks!
