### ISSUE TITLE
Garmin connect sync is not working

### ISSUE THREAD

**Issue by itskratos** [cpfair/tapiriik#278]
Hi,

I have been using the tapiriik since some time now. Since a while, Garmin Connect sync is not working. I also tried disconnecting the Garminc Connect, but even the disconnect does not seem to work.

Let me know if some other information is required.

**Comment by sandertuijn** [comment]
It seems i have the same issue. Garmin says last sync 12-12 and i have an activity in strava to add in Garmin. Are there problems?

**Comment by srjinatl** [comment]
I just noticed that garmin is no longer syncing for me as well. The sync is working between strava and runkeeper - but not garmin.

**Comment by srjinatl** [comment]
Looking at my activities - the two that did not sync show this message when I drill into it on the Tapirik site:
There was a problem indexing your activities on Garmin Connect, so no activities will be uploaded to Garmin Connect. 

Anyone know what that means and how to fix it?

**Comment by brucekaskel** [comment]
I run my own online system that accesses data on Garmin Connect. Some of the GC services I use to access user data have been broken since approximately midday (PT) on Tuesday Dec 13. I'm not sure if this is related to tapiriik syncing issues or not. GC has not listed any status problems so they are, for now, apparently unaware of the problems. This morning I finally reported the web API problems I was seeing (in my system) to Garmin support. It's not clear to me these are related to tapiriik issues though the timing seems to be similar.

**Comment by srjinatl** [comment]
Thanks for the update brucekaskel - I think they are in fact related - my activities prior to that date all sync'd just fine. Hopefully someone on the Garmin side will things back up and running soon...

**Comment by khertan** [comment]
Hi,

It s look like they change their pre sso auth ... 
        preResp = session.get("https://sso.garmin.com/sso/login", params=params)
        if preResp.status_code != 200:
            raise APIException("SSO prestart error %s %s" % (preResp.status_code, preResp.text))
        data["lt"] = re.search("name=\"lt\"\s+value=\"([^\"]+)\"", preResp.text).groups(1)[0]
there is no name= string in the Garmin answer.

**Comment by jlouder** [comment]
I did some experimenting, and it looks like this call now requires the gauthHost parameter.
`preResp = session.get("https://sso.garmin.com/sso/login", params=params)`

I'm testing this with a Perl module that does the same thing, but it also broke today, and I tried adding in the parameters used in this call when my browser logs in to Garmin Connect one by one. Adding gauthHost did the trick. It looks like that's already there in the code, just commented out, probably because it wasn't required before.

**Comment by khertan** [comment]
Indeed, well found., i was experimenting various changes and params too.
Thank you

**Comment by brucekaskel** [comment]
Yes it is possible it could be related to Auth issues. My system is supposed to alert me if it cannot authorize, however if it *thinks* it has authorized successfully (but it hasn't) then this would also explain the current symptoms I am seeing.

**Comment by khertan** [comment]
Yes it s required now, without, garmin connect return a default page asking for a modern browser...
And so the return page status code is 200 ...

**Comment by brucekaskel** [comment]
Yes, that solved it for me. Thanks!
