### ISSUE TITLE
Broken timezone sync from SmashRun

### ISSUE THREAD

**Issue by widianto** [cpfair/tapiriik#376]
First, I want to thank you by creating such great service to be able to sync run data between various services. I am sorry I able to support you in minimum amount. Again, thanks!

I want to report you about timezone syncing problem from SmashRun to various services. They all can sync perfectly, only the timezone is not synced corrected. In short, all synced run on Strava and Endomondo timezone seems rolled back by -7 hours, while Smashrun is my original timezone. BTW, my timezone is GMT +7.

Screenshots of synced run:
- https://snag.gy/tYW5zR.jpg (SmashRun, original run data, correct time)
- https://snag.gy/8sn0hf.jpg (Strava, synced from Smash Run, time -7 hours)

Based on my history, it looks like happened on commits **after Jun 18, 2017** and **before Jul 10, 2017**. Prior to Jun 18, timezone syncing was okay.

Sorry for my English. Hope I can explain it clearly. Thanks for your help.

Regards,
Arif

**Comment by campbellr** [comment]
I think this *might* be a bug in the smashrun API. If I look at the
response for one of my runs from the API, the time zone for the
`startDateTimeLocal` field shows up as +14 instead of the expected -6.

Even looking at very old runs (which I'm almost positive had the correct
offset originally) I see they have a +14 offset

The same run viewed from the smashrun website has the correct offset.

It might be worth sending an email to hi@smashrun.com

**Comment by chrislukic** [comment]
Thanks for looking into this Ryan. It is indeed a bug with Smashrun API,  and a fairly major one. I'll put a patch together first thing Monday morning and get this sorted out.

**Comment by widianto** [comment]
Thanks, Ryan and Chris.

**Comment by chrislukic** [comment]
This should be fixed now.
